community/PhilTisoni.md

**Descrição**
Adicionando resolução do desafio Profile README proposto pelo bootcamp Potência Tech
- [ x ] Resolução do Desafio Profile README
**Checklist**
- [ x ] Minhas alterações não deletam partes do projeto
- [ x ] Minhas alterações não introduzem novos problemas
- [ x ] Minha contribuição está de acordo com o [Guia de Contribuição](https://github.com/elidianaandrade/dio-lab-open-source/blob/main/CONTRIBUTING.md)
N / A

feat: add PhilTisoni profile

---

community/alexlord19.md

**Descrição**
- [x ] Resolução do Desafio Profile README
**Checklist**
- [x ] Minhas alterações não deletam partes do projeto
- [x ] Minhas alterações não introduzem novos problemas
- [x ] Minha contribuição está de acordo com o [Guia de Contribuição](https://github.com/elidianaandrade/dio-lab-open-source/blob/main/CONTRIBUTING.md)
Perfil criado com base em modelo de terceiros

feat: add alexlord profile

---

community/ThRQuin.md

**Descrição**
Adiciona Profile README da ThRQuin
- [] Correção de bug
**Checklist**
N/A

feat: add ThRQuin profile

---

community/felipemike.md

**Descrição**
Adiciona Profile README.md da Octoeli.
**Checklist**
Estou adicionando meu README.md para a comunidade.

feat: add felipemike profile

---

community/relESCampONes.md

**Descrição**
Adiciona Profile README de relESCampONes
**Checklist**
N/A

feat: add relESCampONes profile

---

community/luuanfaria.md

**Descrição**
Adicionado readme.md community/luuanfaria
**Checklist**

feat: create luuanfaria.md

---

community/dreeilima.md

**Descrição**
Adiciona o profile README do dreeilima
**Checklist**
N/A

feat: add dreeilima profile

---

community/alelessa82.md

**Descrição**
Adiciona o Profile do alelessa82
- [X ] Resolução do Desafio Profile README
**Checklist**
N/A

feat:add alelessa82 profile

---

community/picorelli1979.md

**Descrição**
Profile README de FABRICIO PAIM
- [x ] Resolução do Desafio Profile README
**Checklist**
- [x ] Minhas alterações não deletam partes do projeto
- [x ] Minhas alterações não introduzem novos problemas
- [ x] Minha contribuição está de acordo com o [Guia de Contribuição](https://github.com/elidianaandrade/dio-lab-open-source/blob/main/CONTRIBUTING.md)
Sem Comentários

feat: add picorelli1979 profile

---

community/Tete2703.md

**Descrição**
Profile README Tete2703
- [ x] Resolução do Desafio Profile README
**Checklist**
- [ x] Minhas alterações não deletam partes do projeto
- [x ] Minhas alterações não introduzem novos problemas
N/A

feat: add Tete2703 profile

---

community/orodrigocarielo.md

**Descrição**
Adiciona profile readme de orodrigocarielo
**Checklist**
Feito conforme as aulas

feat: add orodrigocarielo profile

---

community/juliaandreds.md

**Descrição**
Adiciona Profile README da juliaandreds
- [x ] Resolução do Desafio Profile README
**Checklist**
- [x ] Minhas alterações não deletam partes do projeto
- [x ] Minhas alterações não introduzem novos problemas
- [ x] Minha contribuição está de acordo com o [Guia de Contribuição](https://github.com/elidianaandrade/dio-lab-open-source/blob/main/CONTRIBUTING.md)
N/A

feat: add juliaandreds profile

---

community/renataalvescun.md

**Descrição**
Adiciona perfil em markdown para o completar o desafio Profile README.
**Checklist**
N/A

feat: add renataalvescun profile

---

community/laianeoliveiradarocha.md

**Descrição**
Adiciona Profile README da laianeoliveiradarocha.
**Checklist**
N/A.

feat: add laianeoliveiradarocha profile

---

community/BarbosaAugusto.md

**Descrição**
Adiciona o profile README BarbosaAugusto
**Checklist**

feat: add BarbosaAugusto profile

---

community/JuniorAlves05.md

**Descrição**
Adiciona Profile README do JuniorAlves05
**Checklist**
N/A.

feat: add JuniorAlves05 profile

---

community/leitdiego85.md

feat: adicionado arquivo leitdiego85.md

---

community/Cicerofer.md

Adiciona Profile README do Cicerofer
N/A.

feat: add Cicrofer profile

---

community/Marcelllombm.md

Adiciona Profile README do Marcelllombm
N/A.

feat? add Marcelllombm profile

---

community/r0t1v.md

feat: r0t1v profile

---

community/Guimsdev.md

feat: add Guimsdev profile

---

community/danirodrigues90.md

Adiciona profile README da danirodrigues90.

feat: add danirodrigues90 profile

---

community/IgorPio07.md

Adiciona profile README.md de IgorPio07
N/A

feat: add IgorPio07 profile

---

community/pedroheinrich.md

add Pedro Heinrich a comunnity

---

community/jam3lima.md

feat: add jam3lima profile

---

community/RSousa-DS.md

feat: RSousa-DS profile

---

community/leoturinal.md

Adiciona profile README de leoturinal
Coloquei o meu nome na breanch depois percebi que era o nome de usuario, espero que não tenha problema.

feat: add leoturinal profile

---

community/LuisClaudioMelo.md

feat: add LuisClaudioMelo profile

---

community/MaSales08.md

Adiciona Profile README da Maria Eduarda de Sales
N/A

feat: add MaSales08 profile

---

community/kaiojv1.md

Adiciona profile readme kaiojv1
N/A

feat: kaiojv1

---

community/Xuais.md

feat: add Xuais profile

---

community/Kayocma.md

Adiciona profile Readme de Kayocma
N/A.

feat:add Kayocma profile

---

community/RayconBatista.md

Solucionar meu problema do Desafio Profile README.
N/A

fix: update RayconBatista README Profile

---

community/viniciusmull.md

feat: add viniciusmull profile

---

community/LeonardoSarto.md

Created Readme

---

community/victor-godoy.md

feat: add victor-godoy profile

---

community/AlexFelipeHonorio.md

Adiciona Profle README do AlexFelipeHonorio
N/A

feat: add AlexFelipeHonorio profile

---

community/UdenilsonEspiritoSanto.md

atualizacao do desafio contribuindo com projeto open-source

UdenilsonEspiritoSanto.md

---

community/oliveiraDaniel42.md

minha contribuição para o desafio

---

community/williandsl.md

profile williandsl

---

community/Enrico-Meira.md

feat: add Enrico-Meira profile

---

community/alrmarques.md

feat: add alrmarques profile

---

community/jgncs.md

feat: add jgncs profile

---

community/bacmk.md

feat: add bacmk profile

---

community/devsbruno.md

Adiciona Profile README de devsbruno
N/A

feat: add devsbruno profile

---

community/eloilsondosanjos.md

Adiciona Profile README de Eloilson dos Anjos
N/A

feat: add eloilsondosanjos profile

---

community/DavidSousaZ.md

Adição do profile readme(DavidSousaZ)

feat: add DavidSousaZ profile

---

community/Sh4kaa.md

feat: add Sh4kaa profile

---

community/kaoriyasu.md

Contribuição com README

---

community/victorsupradados.md

feat: add victorsupradados profile

---

community/ejunior89.md

feat: add ejunior89 profile

---

community/jojoabs.md

Adiciona Profile README do Jojoabs

feat: add jojoabs profile

---

community/LllMorris.md

feat: add LllMorris profile

---

community/laviniaaaf.md

feat: add laviniaaaf profile

---

community/o-nand.md

feat: add o-nand.md to community

---

community/WillMachado67.md

feat: add WillMachado67 profile

---

community/RomeuPassadoreNeto23.md

feat: add RomeuPassadoreNeto23 profile
